server:
  port: 8080

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    cache: true
    check-template-location: true
    enabled: true

logging:
  config: classpath:logback.xml